[package]
name = "moonlight-installer"
version = "0.2.0"
license = "MIT"
edition = "2021"

[package.metadata.bundle]
name = "moonlight Installer"
identifier = "io.github.moonlight-mod.moonlight-installer"
icon = ["assets/icon.png"]

[dependencies]
anyhow = "1.0.89"
eframe = { version = "0.29.1", features = [
  "accesskit",
  "default_fonts",
  "persistence",
] }
egui = "0.29.1"
env_logger = "0.11.5"
flate2 = "1.0.34"
flume = "0.11.0"
log = "0.4.22"
reqwest = { version = "0.12.8", features = [
  "blocking",
  "json",
  "rustls-tls",
], default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tar = "0.4.42"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1.17"
