[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
clap = { version = "4.5.19", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
log = "0.4.22"
env_logger = "0.11.5"
