name: Build
on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --bin moonlight-installer --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-installer-windows
          path: target/release/moonlight-installer.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build
        run: cargo build --bin moonlight-installer --release
      - name: Bundle
        run: cargo bundle --bin moonlight-installer --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-installer-macos
          path: target/release/bundle
