name: Build
on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-installer-windows
          path: target/release/moonlight-installer.exe

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build AppImage
        run: ./build-linux.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-installer-linux
          path: ./moonlight-installer-x86_64.AppImage

  # TODO: macOS
  # build-macos: